/**
 * @file app.config.ts
 * @description Per-game visual identity. Generated by tools/propagate-theme.js.
 * Edit the source script and re-run to update.
 */
export const APP_CONFIG = {
  name: "Scopa",
  primary: "#F59E0B",
  secondary: "#B45309",
  splash: {
    glow: "rgba(180,83,9,0.6)",
    sallyGlow: "rgba(245,158,11,0.8)",
    pillBorder: "rgba(245,158,11,0.5)",
    pillBg: "rgba(180,83,9,0.15)",
    pillText: "#FEF3C7",
    suit: "🇮🇹",
    suit2: "✦",
  },
  slides: {
    slide2: { tint: ["rgba(245,158,11,0.55)","rgba(180,83,9,0.7)","rgba(40,20,5,0.95)"], variant: "fan" },
    slide3: { tint: ["rgba(217,119,6,0.45)","rgba(120,53,15,0.85)","rgba(40,20,5,0.95)"], variant: "scattered" },
    slide4: { tint: ["rgba(34,197,94,0.45)","rgba(245,158,11,0.7)","rgba(40,20,5,0.95)"], variant: "grid" },
  },
} as const;

export type SlideVariant = 'fan' | 'scattered' | 'spread' | 'grid';
